services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Ibexa\Bundle\DesignSystemTwig\Templating\Twig\CssClassExtension:
        tags:
            - { name: twig.extension }

    Ibexa\Bundle\DesignSystemTwig\Templating\Twig\TemplateExtension:
        tags:
            - { name: twig.extension }
